# Generated by Django 5.2.4 on 2025-07-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='color',
            new_name='box_size',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='purpose_of_plastic',
            new_name='material_type',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='quantity',
            new_name='ocean_depth_range',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='transparency',
            new_name='seagrass_type',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='type_of_plastic',
        ),
    ]
