# Generated by Django 5.2.4 on 2025-07-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0002_rename_color_hydra_box_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_color',
            new_name='decrypted_box_size',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_purpose_of_plastic',
            new_name='decrypted_material_type',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_quantity',
            new_name='decrypted_ocean_depth_range',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_transparency',
            new_name='decrypted_seagrass_type',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_type_of_plastic',
            new_name='encrypted_box_size',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_color',
            new_name='encrypted_material_type',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_purpose_of_plastic',
            new_name='encrypted_ocean_depth_range',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_quantity',
            new_name='encrypted_seagrass_type',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_transparency',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_type_of_plastic',
        ),
    ]
