# Generated by Django 5.2.4 on 2025-07-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0003_rename_decrypted_color_hydra_decrypted_box_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='guanidinium_monomers',
            new_name='surface_area_of_box',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='sodium_hexametaphosphate',
            new_name='volume_of_material',
        ),
        migrations.AddField(
            model_name='hydra',
            name='weight_in_kilograms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='weight_of_material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hydra',
            name='material_type',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
