# Generated by Django 5.2.4 on 2025-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0004_rename_guanidinium_monomers_hydra_surface_area_of_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_guanidinium_monomers',
            new_name='decrypted_surface_area_of_box',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_sodium_hexametaphosphate',
            new_name='decrypted_volume_of_material',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_guanidinium_monomers',
            new_name='decrypted_weight_in_kilograms',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_sodium_hexametaphosphate',
            new_name='decrypted_weight_of_material',
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_surface_area_of_box',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_volume_of_material',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_weight_in_kilograms',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_weight_of_material',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
