# Generated by Django 5.2.4 on 2025-07-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0005_rename_decrypted_guanidinium_monomers_hydra_decrypted_surface_area_of_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydra',
            name='material_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
