# Generated by Django 5.2.4 on 2025-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0006_alter_hydra_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='dissolving_time_in_saltwater',
            new_name='durability_score',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='flexibilty_testing',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='strength_calculation',
        ),
        migrations.AddField(
            model_name='hydra',
            name='leakage_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hydra',
            name='leakage_pass',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='pressure_bar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='pressure_pass',
            field=models.BooleanField(null=True),
        ),
    ]
