# Generated by Django 5.2.4 on 2025-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0007_rename_dissolving_time_in_saltwater_hydra_durability_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_dissolving_time_in_saltwater',
            new_name='decrypted_durability_score',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_flexibilty_testing',
            new_name='decrypted_leakage_pass',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='decrypted_strength_calculation',
            new_name='decrypted_pressure_bar',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='encrypted_dissolving_time_in_saltwater',
            new_name='decrypted_pressure_pass',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_flexibilty_testing',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_strength_calculation',
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_durability_score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_leakage_pass',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_pressure_bar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_pressure_pass',
            field=models.TextField(null=True),
        ),
    ]
