# Generated by Django 5.2.4 on 2025-07-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0008_rename_decrypted_dissolving_time_in_saltwater_hydra_decrypted_durability_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydra',
            old_name='coating_volume',
            new_name='available_seed_space',
        ),
        migrations.RenameField(
            model_name='hydra',
            old_name='coating_weight',
            new_name='seed_growth_time',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='total_surface_area',
        ),
    ]
