# Generated by Django 5.2.4 on 2025-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0009_rename_coating_volume_hydra_available_seed_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydra',
            name='decrypted_coating_volume',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='decrypted_coating_weight',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='decrypted_total_surface_area',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_coating_volume',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_coating_weight',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='encrypted_total_surface_area',
        ),
        migrations.AddField(
            model_name='hydra',
            name='decrypted_available_seed_space',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='decrypted_seed_growth_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_available_seed_space',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='encrypted_seed_growth_time',
            field=models.TextField(null=True),
        ),
    ]
