# Generated by Django 5.2.4 on 2025-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0010_remove_hydra_decrypted_coating_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydra',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='hydra',
            name='quality_of_plastic',
        ),
        migrations.AddField(
            model_name='hydra',
            name='animals_supported',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='area_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='co2_absorbed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydra',
            name='protection_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
